// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tb__xbar_connect generated by `tlgen.py` tool

xbar_peri dut();

`DRIVE_CLK(clk_main_i)
`DRIVE_CLK(clk_io_i)

initial force dut.clk_main_i = clk_main_i;
initial force dut.clk_io_i = clk_io_i;

// TODO, all resets tie together
initial force dut.rst_main_ni = rst_n;
initial force dut.rst_io_ni = rst_n;

// Host TileLink interface connections
`CONNECT_TL_HOST_IF(axi_xbar, dut, clk_main_i, rst_n)

// Device TileLink interface connections
`CONNECT_TL_DEVICE_IF(rom_ctrl_rom, dut, clk_io_i, rst_n)
