// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_peri_bind module generated by `tlgen.py` tool for assertions
module xbar_peri_bind;
`ifndef GATE_LEVEL
  // Host interfaces
  bind xbar_peri tlul_assert #(.EndpointType("Device")) tlul_assert_host_axi_xbar (
    .clk_i  (clk_main_i),
    .rst_ni (rst_main_ni),
    .h2d    (tl_axi_xbar_i),
    .d2h    (tl_axi_xbar_o)
  );

  // Device interfaces
  bind xbar_peri tlul_assert #(.EndpointType("Host")) tlul_assert_device_rom_ctrl_rom (
    .clk_i  (clk_io_i),
    .rst_ni (rst_io_ni),
    .h2d    (tl_rom_ctrl_rom_o),
    .d2h    (tl_rom_ctrl_rom_i)
  );
`endif
endmodule
