// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"rom_ctrl_rom", '{
        '{32'h00080000, 32'h0009ffff}
    }},
    '{"gpio", '{
        '{32'h40000000, 32'h4000ffff}
    }},
    '{"rom_ctrl_regs", '{
        '{32'h40060000, 32'h4006ffff}
    }},
    '{"uart", '{
        '{32'h41000000, 32'h41000fff}
    }},
    '{"spi_device", '{
        '{32'h43000000, 32'h43001fff}
    }},
    '{"timer", '{
        '{32'h44000000, 32'h4400ffff}
    }},
    '{"plic", '{
        '{32'h48000000, 32'h4bffffff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"axi_xbar", 0, '{
        "gpio",
        "rom_ctrl_rom",
        "rom_ctrl_regs",
        "uart",
        "spi_device",
        "timer",
        "plic"}}
};
