// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `rdl2ot` containing data structure

package SIM_CTRL_reg_pkg;

  // Address widths within the block

  // Number of registers for every interface

endpackage
