// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_peri module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// axi_xbar
//   -> asf_2
//     -> rom_ctrl_rom

module xbar_peri (
  input clk_main_i,
  input clk_io_i,
  input rst_main_ni,
  input rst_io_ni,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_axi_xbar_i,
  output tlul_pkg::tl_d2h_t tl_axi_xbar_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_rom_ctrl_rom_o,
  input  tlul_pkg::tl_d2h_t tl_rom_ctrl_rom_i,

  input prim_mubi_pkg::mubi4_t scanmode_i
);

  import tlul_pkg::*;
  import tl_peri_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  logic unused_scanmode;
  assign unused_scanmode = ^scanmode_i;

  tl_h2d_t tl_asf_2_us_h2d ;
  tl_d2h_t tl_asf_2_us_d2h ;
  tl_h2d_t tl_asf_2_ds_h2d ;
  tl_d2h_t tl_asf_2_ds_d2h ;



  assign tl_rom_ctrl_rom_o = tl_asf_2_ds_h2d;
  assign tl_asf_2_ds_d2h = tl_rom_ctrl_rom_i;

  assign tl_asf_2_us_h2d = tl_axi_xbar_i;
  assign tl_axi_xbar_o = tl_asf_2_us_d2h;


  // Instantiation phase
  tlul_fifo_async #(
    .ReqDepth        (1),
    .RspDepth        (1)
  ) u_asf_2 (
    .clk_h_i      (clk_main_i),
    .rst_h_ni     (rst_main_ni),
    .clk_d_i      (clk_io_i),
    .rst_d_ni     (rst_io_ni),
    .tl_h_i       (tl_asf_2_us_h2d),
    .tl_h_o       (tl_asf_2_us_d2h),
    .tl_d_o       (tl_asf_2_ds_h2d),
    .tl_d_i       (tl_asf_2_ds_d2h)
  );

endmodule
