# Copyright lowRISC Contributors (COSMIC project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Nightly

on:
  schedule:
    - cron: "00 02 * * *"

jobs:
  slow-verilator-test:
    runs-on: ["self-hosted", "nixos", "X64"]

    steps:
      - uses: actions/checkout@v5

      - name: Prepare Nix environment
        run: nix run .#ci -- warmup

      - name: Slow Verilator tests
        run: nix run .#ci -- verilator-slow-test
